### ISSUE TITLE
骚年你定义变量也不怕自动分号机制么

### ISSUE THREAD

**Issue by QingWei-Li** [hanaarena/learnyounode_code#1]
var a = 1
 ,b = 2;

这样写合适么 = =

**Comment by hanaarena** [comment]
werstorm下照上面格式写的话会自动格式化成下面的形式

``` javascript
var a = 1
    , b = 2
```

可是ST下是

``` javascript
var a = 1
  , b = 2
```

怪我咯(\* ￣︿￣)

**Comment by QingWei-Li** [comment]
I mean 不应该是定义几个变量就用几个var么，额反正个人风格么，感觉怪怪的

2015-04-06 17:03 GMT+08:00, Lanz notifications@github.com:

**Comment by hanaarena** [comment]
个人习惯~

在 2015年4月6日 下午5:08，cinwell.li notifications@github.com写道：
